### ISSUE TITLE
AttributeError in plot_model for 2D Cluster PCA Plot

### ISSUE THREAD

**Issue by mtdearing** [pycaret/pycaret#317]
For a clustering model I've been working on with pycaret pre-2.0, I was generating the PCA plot successfully. I updated to 2.0, and receive the error below when running plot_model(<my_model>, plot='cluster').  The other plot types, e.g., 'elbow', generate a plot output without an error. Does the error below suggest I would have a feature format issue in my dataset?

```
~/miniconda3/lib/python3.7/site-packages/pycaret/clustering.py in plot_model(model, plot, feature, label, save, system)
   3416 
   3417         for i in pca_.Cluster:
-> 3418             a = int(i.split()[1])
   3419             clus_num.append(a)
   3420 

AttributeError: 'float' object has no attribute 'split'
```

**Comment by pycaret** [comment]
@mtdearing Could be due to some formatting issues. I cannot reproduce the error on different datasets. Can you please share "logs.log" file generated in the working directory along with sample dataset? I can have a look into it. Most likely a bug that needs to be fixed.

**Comment by caiquefilipini** [comment]
> For a clustering model I've been working on with pycaret pre-2.0, I was generating the PCA plot successfully. I updated to 2.0, and receive the error below when running plot_model(<my_model>, plot='cluster'). The other plot types, e.g., 'elbow', generate a plot output without an error. Does the error below suggest I would have a feature format issue in my dataset?
> 
> ```
> ~/miniconda3/lib/python3.7/site-packages/pycaret/clustering.py in plot_model(model, plot, feature, label, save, system)
>    3416 
>    3417         for i in pca_.Cluster:
> -> 3418             a = int(i.split()[1])
>    3419             clus_num.append(a)
>    3420 
> 
> AttributeError: 'float' object has no attribute 'split'
> ```

I had the same error. Probably your index are shuffled. Try ".reset_index(drop=True)" and run again. For me it works.

**Comment by mtdearing** [comment]
@pycaret Thanks for taking a look. I appreciate that it is not possible to debug very far, especially as this could be an issue with my data formatting. I re-ran after trying @caiquefilipini recommendation to .reset_index (no success) and made sure my data only included int64 and object (text strings) (e.g., no floats). This is the output into the log immediate after running plot_model(<my_model>):

2020-08-06 06:18:07,255:INFO:Initializing plot_model()
2020-08-06 06:18:07,256:INFO:plot_model(model=KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=-1, precompute_distances='deprecated',
       random_state=123, tol=0.0001, verbose=0), plot=cluster, feature=None, label=False, save=False, system=True)
2020-08-06 06:18:07,257:INFO:Checking exceptions
2020-08-06 06:18:07,257:INFO:Importing libraries
2020-08-06 06:18:07,274:INFO:plot type: cluster
2020-08-06 06:18:07,275:INFO:SubProcess assign_model() called ==================================
2020-08-06 06:18:07,276:INFO:Initializing assign_model()
2020-08-06 06:18:07,277:INFO:assign_model(model=KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=4, n_init=10, n_jobs=-1, precompute_distances='deprecated',
       random_state=123, tol=0.0001, verbose=0), transformation=True, verbose=False)
2020-08-06 06:18:07,277:INFO:Checking exceptions
2020-08-06 06:18:07,277:INFO:Preloading libraries
2020-08-06 06:18:07,278:INFO:Copying data
2020-08-06 06:18:07,278:INFO:Transformation param set to True. Assigned clusters are attached on transformed dataset.
2020-08-06 06:18:07,279:INFO:Preparing display monitor
2020-08-06 06:18:07,332:INFO:Determining Trained Model
2020-08-06 06:18:07,335:INFO:Trained Model : K-Means Clustering
2020-08-06 06:18:07,335:INFO:(156, 178)
2020-08-06 06:18:07,335:INFO:assign_model() succesfully completed......................................
2020-08-06 06:18:07,335:INFO:SubProcess assign_model() end ==================================
2020-08-06 06:18:07,446:INFO:Fitting PCA()
2020-08-06 06:18:07,465:INFO:Sorting dataframe

**Comment by mtdearing** [comment]
@pycaret RESOLVED: I added a new index column to my data set, and re-set it with .reset_index(drop=True) for good measure, and it worked. So, I must have been running with an index that did not include well-defined integer values. Thank you!

**Comment by pycaret** [comment]
Thanks.
