### ISSUE TITLE
[BUG]: Pipeline Plot in evaluate_model doesnt work

### ISSUE THREAD

**Issue by EdgarEAM** [pycaret/pycaret#3486]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Pipeline Plot in evaluate_model returns TypeError: Drawing.draw() got an unexpected keyword argument 'ax', and a blank graph 
![Screenshot_7](https://user-images.githubusercontent.com/128922009/232829978-c65e926d-d965-4a7f-b890-a92045a6d647.png)

### Reproducible Example

```python
import pycaret
import pandas as pd
## Load Data
data = pd.read_csv("insurance.csv")
#same as dataset pycaret

# import pycaret regression and init setup
from pycaret.regression import *
s = setup(data, target = 'charges', session_id = 123)

# compare baseline models
best = compare_models()
evaluate_model(estimator=best)
```

### Expected Behavior

Show Pipeline Plot of desired model

### Actual Results

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\ipywidgets\widgets\interaction.py in update(self, *args)
    255                     value = widget.get_interact_value()
    256                     self.kwargs[widget._kwarg] = value
--> 257                 self.result = self.f(**self.kwargs)
    258                 show_inline_matplotlib_plots()
    259                 if self.auto_display and self.result is not None:

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\pycaret\internal\pycaret_experiment\tabular_experiment.py in _plot_model(self, estimator, plot, scale, save, fold, fit_kwargs, plot_kwargs, groups, feature_name, label, use_train_data, verbose, system, display, display_format)
   1942                 # execute the plot method
   1943                 with redirect_output(self.logger):
-> 1944                     ret = locals()[plot]()
   1945                 if ret:
   1946                     plot_filename = ret

~\anaconda3\envs\PyC3_0_0Full\lib\site-packages\pycaret\internal\pycaret_experiment\tabular_experiment.py in pipeline()
    574                         )
    575 
--> 576                         d.draw(ax=ax, showframe=False, show=False)
    577                         ax.set_aspect("equal")
    578                         plt.axis("off")

TypeError: Drawing.draw() got an unexpected keyword argument 'ax'
```

### Installed Versions

<details>
'3.0.0'
</details>

**Comment by tvdboom** [comment]
what version of the `schemdraw` library are you using?

**Comment by EdgarEAM** [comment]
It works with schemdraw ==0.15

I guess schemdraw 0.16 was installed along with pycaret==3.0.0

Feel free to close this issue
