### ISSUE TITLE
SimpleImputer object has no attiribute validate data 

### ISSUE THREAD

**Issue by rananuryavuz** [pycaret/pycaret#823]
I would like to use my data set with anomaly detection library but I got this error all the time which is in enclosed file.
![pycaret](https://user-images.githubusercontent.com/22149365/98520570-45150e00-2283-11eb-9087-e3d1c7888c48.PNG)

**Comment by Yard1** [comment]
Is it possible for you to share the code and dataset?

**Comment by rananuryavuz** [comment]
pip install pycaret[full]
from pycaret.anomaly import *
exp_name = setup(data = df2)


Sample from the dataset
date                      | value
01.12.19 00:20:55 | 33.77
01.12.19 00:21:55 | 38.49
01.12.19 00:22:55 | 45.27
01.12.19 00:23:55 | 50.72
01.12.19 00:24:55 | 55.27
01.12.19 00:25:55 | 58.09
01.12.19 00:26:55 | 60.32
01.12.19 00:27:55 | 62.16
01.12.19 00:28:55 | 63.67
01.12.19 00:29:55 | 64.32
01.12.19 00:30:55 | 65.21
01.12.19 00:31:55 | 65.51
01.12.19 00:32:55 | 65.58
01.12.19 00:33:55 | 66
01.12.19 00:34:55 | 66.52

**Comment by muyonaise** [comment]
I found I had this error when I used the sklearn.model_selection.train_test_split module on the same dataset

**Comment by rananuryavuz** [comment]
Great Can you please brighten me ?

**Comment by Yard1** [comment]
@muyonaise @rananuryavuz Could you share your `logs.log` files? It's generated in the directory from which you run the notebook/script.

**Comment by coksvictoria** [comment]
I am having the same issue just with the sample dataset and code....

------------------------------code------------------------
#check version
from pycaret.utils import version
print(version())

df=get_data('juice')

from pycaret.classification import *
clf1 = setup(df, target = 'Purchase',session_id=123)


Here below is the log
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-69-b1b0484888dc> in <module>()
      6 
      7 from pycaret.classification import *
----> 8 clf1 = setup(df, target = 'Purchase',session_id=123)

9 frames
/usr/local/lib/python3.6/dist-packages/pycaret/classification.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    652         verbose=verbose,
    653         profile=profile,
--> 654         profile_kwargs=profile_kwargs,
    655     )
    656 

/usr/local/lib/python3.6/dist-packages/pycaret/internal/tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
   1306             test_data = pd.concat([X_test, y_test], axis=1)
   1307 
-> 1308         train_data = prep_pipe.fit_transform(train_data)
   1309         # workaround to also transform target
   1310         dtypes.final_training_columns.append(target)

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in fit_transform(self, X, y, **fit_params)
    365         """
    366         fit_params_steps = self._check_fit_params(**fit_params)
--> 367         Xt = self._fit(X, y, **fit_params_steps)
    368 
    369         last_step = self._final_estimator

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in _fit(self, X, y, **fit_params_steps)
    294                 message_clsname='Pipeline',
    295                 message=self._log_message(step_idx),
--> 296                 **fit_params_steps[name])
    297             # Replace the transformer of the step with the fitted
    298             # transformer. This is necessary when loading the transformer

/usr/local/lib/python3.6/dist-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    350 
    351     def __call__(self, *args, **kwargs):
--> 352         return self.func(*args, **kwargs)
    353 
    354     def call_and_shelve(self, *args, **kwargs):

/usr/local/lib/python3.6/dist-packages/sklearn/pipeline.py in _fit_transform_one(transformer, X, y, weight, message_clsname, message, **fit_params)
    738     with _print_elapsed_time(message_clsname, message):
    739         if hasattr(transformer, 'fit_transform'):
--> 740             res = transformer.fit_transform(X, y, **fit_params)
    741         else:
    742             res = transformer.fit(X, y, **fit_params).transform(X)

/usr/local/lib/python3.6/dist-packages/pycaret/internal/preprocess.py in fit_transform(self, dataset, y)
    565     def fit_transform(self, dataset, y=None):
    566         data = dataset
--> 567         self.fit(data)
    568         return self.transform(data)
    569 

/usr/local/lib/python3.6/dist-packages/pycaret/internal/preprocess.py in fit(self, dataset, y)
    511 
    512         if not self.numeric_columns.empty:
--> 513             self.numeric_imputer.fit(data[self.numeric_columns])
    514             statistics.append((self.numeric_imputer.statistics_, self.numeric_columns))
    515         if not self.categorical_columns.empty:

/usr/local/lib/python3.6/dist-packages/sklearn/impute/_base.py in fit(self, X, y)
    275         self : SimpleImputer
    276         """
--> 277         X = self._validate_input(X, in_fit=True)
    278         super()._fit_indicator(X)
    279 

/usr/local/lib/python3.6/dist-packages/sklearn/impute/_base.py in _validate_input(self, X, in_fit)
    239 
    240         try:
--> 241             X = self._validate_data(X, reset=in_fit,
    242                                     accept_sparse='csc', dtype=dtype,
    243                                     force_all_finite=force_all_finite,

AttributeError: 'SimpleImputer' object has no attribute '_validate_data'

**Comment by Yard1** [comment]
@coksvictoria Can you share the entire notebook?

**Comment by coksvictoria** [comment]
> @coksvictoria Can you share the entire notebook?

Thank you for prompt reply... I have just had another run, somehow the issue was gone..

**Comment by XinQi7788** [comment]
I have the same error. Please let me know how to fix the error? Thank you very much.

**Comment by Yard1** [comment]
@XinQi7788 Can you share code and dataset to reproduce this error?

**Comment by XinQi7788** [comment]
Hi Antoni:

I attached the log, data and code.


When I changed to pip install pycaret[full], another error comes out: ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.


Please help me how it and really want to use Pycaret for our study.

Thank you very much and looking forward to your reply.

Best
Xin

**Comment by Yard1** [comment]
> When I changed to pip install pycaret[full], another error comes out: ValueError: Setting a random_state has no effect since shuffle is False. You should leave random_state to its default (None), or set shuffle=True.

That will be fixed in an update which should be out in the next couple days.

Also, I do not think attaching files worked. Can you upload them somewhere and post a link to them? Thanks.

**Comment by DesiKeki** [comment]
I am getting a similar error, but for another attribute 'target_variable'

```
clu1 = setup(data=df_train)

AttributeError: 'Simple_Imputer' object has no attribute 'target_variable'
```

PyCaret version: 2.0

**Comment by juandpinto** [comment]
Not sure if this is related, but I'm also getting a similar error:

```
reg_exp = setup(data=df, target='score', session_id=42)

AttributeError: 'Simple_Imputer' object has no attribute 'fill_value_categorical'
```

Using PyCaret 2.3.

**Comment by Yard1** [comment]
Can you share the datasets you are using?

**Comment by PranayMehta** [comment]
I had created a model and stored it as a pickle file in S3. I had put this model in production and I recently also started observing error while trying to generate predictions on unseen data.

`unseen_predictions = predict_model(saved_model, data = finaldf_pandas)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/load_packages1/python_packages_folder/pycaret/classification.py", line 10605, in predict_model
    model_name = str(estimator).split("(")[0]
  File "/tmp/load_packages1/python_packages_folder/sklearn/base.py", line 260, in __repr__
    repr_ = pp.pformat(self)
  File "/usr/lib64/python3.6/pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/usr/lib64/python3.6/pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "/usr/lib64/python3.6/pprint.py", line 393, in _repr
    self._depth, level)
  File "/tmp/load_packages1/python_packages_folder/sklearn/utils/_pprint.py", line 181, in format
    changed_only=self._changed_only)
  File "/tmp/load_packages1/python_packages_folder/sklearn/utils/_pprint.py", line 437, in _safe_repr
    v, context, maxlevels, level, changed_only=changed_only)
  File "/tmp/load_packages1/python_packages_folder/sklearn/utils/_pprint.py", line 406, in _safe_repr
    o, context, maxlevels, level, changed_only=changed_only)
  File "/tmp/load_packages1/python_packages_folder/sklearn/utils/_pprint.py", line 406, in _safe_repr
    o, context, maxlevels, level, changed_only=changed_only)
  File "/tmp/load_packages1/python_packages_folder/sklearn/utils/_pprint.py", line 425, in _safe_repr
    params = _changed_params(object)
  File "/tmp/load_packages1/python_packages_folder/sklearn/utils/_pprint.py", line 91, in _changed_params
    params = estimator.get_params(deep=False)
  File "/tmp/load_packages1/python_packages_folder/sklearn/base.py", line 195, in get_params
    value = getattr(self, key)
AttributeError: 'Simple_Imputer' object has no attribute 'target_variable'`

I am using pycaret version 2.0.0 and my model has also been trained on this version. 


import pycaret
pycaret.__version__
'2.0.0'

**Comment by Yard1** [comment]
There have been a number of changes since pycaret version 2.0.0. Can you update to the newest version, recreate the pipeline and try again? The saved pipeline will sadly not work.

**Comment by PranayMehta** [comment]
> There has been a number of changes since pycaret version 2.0.0. Can you update to the newest version, recreate the pipeline and try again? The saved pipeline will sadly not work.

@Yard1 Will the same pipeline work on pycaret 2.3 version? The reason why I ask is because I have a model that was trained on 2.0 and I dont want to lose that model. That model is very important from our production pipeline perspective and I will need to understand whether or not the same model will work on the 2.3 pycaret version.

**Comment by PranayMehta** [comment]
@Yard1 @pycaret When I installed the latest version of pycaret(2.3), then I get below error when I load the pickle model.

```
import boto3
s3 = boto3.resource('s3')
s3.Bucket('bucket-name').download_file('s3path', '/tmp/model.pkl')
model_path = '/tmp/model'

>>> from pycaret.classification import *
>>> saved_model = load_model(model_path)    
Transformation Pipeline and Model Successfully Loaded
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hadoop/tutorial-env/lib/python3.6/dist-packages/pycaret/classification.py", line 2163, in load_model
    verbose=verbose,
  File "/home/hadoop/tutorial-env/lib/python3.6/dist-packages/pycaret/internal/tabular.py", line 9015, in load_model
    model_name, platform, authentication, verbose
  File "/home/hadoop/tutorial-env/lib/python3.6/dist-packages/pycaret/internal/persistence.py", line 373, in load_model
    return joblib.load(model_name)
  File "/home/hadoop/tutorial-env/lib/python3.6/dist-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/hadoop/tutorial-env/lib/python3.6/dist-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/lib64/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "/usr/lib64/python3.6/pickle.py", line 1338, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib64/python3.6/pickle.py", line 1388, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pycaret.preprocess'
>>> print("model loaded")
model loaded
>>> import pycaret
>>> pycaret.__version__
'2.3.0'
```

My model was trained on pycaret2.0 and now I am stuck because of this issue. Any help is much appreciated.

**Comment by Yard1** [comment]
No, it will not work. Sorry for that.

**Comment by PranayMehta** [comment]
> No, it will not work. Sorry for that.

No worries. thank u for the quick response. I think I have made it work somehow.  I am testing this out currently.

**Comment by raultomasmora** [comment]
I was getting this error using pycaret==2.2.1 and streamlit==0.71.0 versions.
AttributeError: 'Simple_Imputer' object has no attribute 'fill_value_categorical'.

I fixed the problem by forcing scikit-learn version==0.23.2

**Comment by PythonTrader88** [comment]
> 
> 
> I was getting this error using pycaret==2.2.1 and streamlit==0.71.0 versions.
> AttributeError: 'Simple_Imputer' object has no attribute 'fill_value_categorical'.
> 
> I fixed the problem by forcing scikit-learn version==0.23.2

Same issue on pycaret==2.3
Forcing scikit-learn version==0.23.2 solved the issue as well

Thanks man!

**Comment by juandpinto** [comment]
> Can you share the datasets you are using?

I'm afraid I can't for privacy reasons. However, like others have already suggested here, I was also able to bypass this problem by forcing `scikit-learn version==0.23.2`.

**Comment by samuelmoss** [comment]
Would this be solved by updating your deployment of pycaret to require sci-kit learn >=0.24.0? Right now pycaret "requires" 0.23.2 according to pip's dependency resolver but these errors are happening when someone has 0.24.0 or above.

**Comment by samuelmoss** [comment]
I forced my scikit version to 0.23.2 and that fixes the pipelining/transformations errors seen in this issue. There's another existing issue if you use 0.23.2 scikit-learn in Logistic Regression where you get an AttributeError saying that the message has no attribute 'decode'.

I personally went and updated my sklearn.utils.optimize.py to mirror the logic after line 230 here https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/utils/optimize.py and that will fix the errors thrown until pycaret catches up to the current versions of their requirements.

**Comment by pycaret** [comment]
@samuelmoss Can you reproduce the `LogisticRegression` error with sklearn==0.23.2? It will be helpful to know. I haven't encountered that error yet.

**Comment by samuelmoss** [comment]
The error happens when you run LR with sklearn==0.23.2 and scipy>=1.6.0 because in the upgraded scipy the result message for solver "lbfgs" is already decoded when optimize.py is called in sklearn. So it will raise an Attribute error saying that it has no attribute 'decode' anytime you're working with LR under the above conditions in PyCaret. They fixed this in sklearn>=0.24.0 to use a try except catch shown from lines 231 - 255 here: 
https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/utils/optimize.py

Instead of downgrading my scipy I just updated the optimize.py in my sklearn==0.23.2 locally to mirror the same try except they use in the above link.

I hope that helps answer your question!

**Comment by jaeho3690** [comment]
I am still getting the error **AttributeError: 'Simple_Imputer' object has no attribute 'fill_value_categorical'**
even after I have installed the below version :(

scikit-learn              0.24.0
pycaret                   2.3.0

**Comment by ngupta23** [comment]
Please downgrade to `scikit` 0.23. 0.24 is not yet supported.

**Comment by igorkf** [comment]
For me the problem was not solved by downgrading `scikit` to 0.23
I tried as well setting `imputation_type='iterative'` and now I got another problem: `ModuleNotFoundError: No module named 'sklearn.kernel_ridge'`
