### ISSUE TITLE
Prediction with Saved Model Attribute Error

### ISSUE THREAD

**Issue by Wookloo** [pycaret/pycaret#525]
Hello,

I have an issue when trying to re use my saved regression Model.
I have been able to create use and save my model within the same session. 
However after i stop my session and want to load previously save model and make new prediction as per the Tutorial. 
I am loading the Model succesfully but after typing the cmd "predict_model" I'm getting an an "Attribute error"
![image](https://user-images.githubusercontent.com/36540215/91018996-edbbb600-e622-11ea-85dd-00e2665549ce.png)

![image](https://user-images.githubusercontent.com/36540215/91019106-10e66580-e623-11ea-956f-a8133b14efb4.png)

I am getting this error on the computer i have develop the model in and the sample of data i m doing the prediction have the same frame/attributes only the size changed compare the previous prediction done successfully.

Here is my pip and pd version 
![image](https://user-images.githubusercontent.com/36540215/91020133-a9c9b080-e624-11ea-8e7e-a5612b3c9149.png)

Thanks for your help!

**Comment by pycaret** [comment]
@Wookloo Is it possible to share the data so that I can try to reproduce this error?

**Comment by Wookloo** [comment]
Hi pycaret.,

Here is my file i give you an extract of what i use.
Dataforexample.xlsx is the data i use to train the model (an extract of it), in my setup "target = Vol."
Prediction.xlsx is the subset of data i was trying to predict the value for prediction that's why there is no "Vol." Column

Let me know if you need anything.



[Prediction.xlsx](https://github.com/pycaret/pycaret/files/5127212/Prediction.xlsx)
[Dataforexample.xlsx](https://github.com/pycaret/pycaret/files/5127235/Dataforexample.xlsx)

**Comment by pycaret** [comment]
@Wookloo Thanks.

I tried to reproduce this issue but I cant. See below:

![image](https://user-images.githubusercontent.com/58118658/91307710-510d2b80-e77c-11ea-8cff-b07b86a80450.png)

Here is output from my logs.log file which shows my environment and the major dependencies:

![image](https://user-images.githubusercontent.com/58118658/91307842-78fc8f00-e77c-11ea-9e69-70687ffe9d23.png)

Let me know if this helps?

**Comment by Wookloo** [comment]
Thanks for your quick reply.

Still not working for me... I check the environment and all my library version seems updated
![image](https://user-images.githubusercontent.com/36540215/91378086-2beaec80-e852-11ea-8b16-b6f966c3e31f.png)

I m attaching the fill error message log in a "Series Object has no attribute _data.txt"
[Series Object has no attribute _data.txt](https://github.com/pycaret/pycaret/files/5133729/Series.Object.has.no.attribute._data.txt)

As well i try load another xgboost model and got this error as well (attached the full message "XGBoostError.txt"
![image](https://user-images.githubusercontent.com/36540215/91377709-cb5baf80-e851-11ea-9872-97d60f83fdef.png)
[XGBoostError.txt](https://github.com/pycaret/pycaret/files/5133733/XGBoostError.txt)

Is something went wrong when saving my model ?

**Comment by saitej123** [comment]
I am also facing similar issue. please check this '

https://github.com/pycaret/pycaret/issues/571

**Comment by saitej123** [comment]
test case: read pkl file in new notebook, create dummy dataframe with input. try predict, it throws error .

**Comment by pycaret** [comment]
@saitej123 Which version of PyCaret are you using? Recently in `2.1` we have changed the behavior of `Pipeline` so if you have trained your model using older version of PyCaret and then updated your environment to the recent version, this may cause an issue.

**Comment by saitej123** [comment]
@pycaret  Hi, I did re train with 2.1 version, still facing the same issue . is there any hack to solve this "AttributeError: 'Empty' object has no attribute 'p_transform_target'" 

 target_transformer = estimator.steps[13][1].p_transform_target # make it dynamic instead of hardcoding no 13

**Comment by pycaret** [comment]
@saitej123 I am unable to reproduce this issue on my end. Can you please attach your Notebook that used for training and code that used for inference here? Thanks

**Comment by saitej123** [comment]
https://github.com/saitej123/ML-APP-HEROKU

Please check this repo, app.py , notebook and dependency files attached here

**Comment by pycaret** [comment]
@saitej123 Thanks. I have now figured out the issue. It's a bug, I have fixed this and will shortly release `2.1.2` on `PyPi`. I will ask you to please retest after the update. Thanks

**Comment by pycaret** [comment]
@Wookloo @saitej123 After updating my version `pycaret==2.1.2` this works fine now. 

![image](https://user-images.githubusercontent.com/58118658/91745355-d9c70580-eb88-11ea-921a-62b39b82f4b8.png)

Thank you for reporting the bug.

**Comment by saitej123** [comment]
Thank you for the update !!

cheers,
sai

**Comment by Wookloo** [comment]
Thanks for fixing the bug.
After i update my pycaret to 2.1.2 should I train and save another model ? or I can use the model i save before ?

**Comment by Wookloo** [comment]
I confirm it works for me too I had to create another model and was able to load it afterwards on a different machine and environment.

Thanks again
