### ISSUE TITLE
[BUG]: failed to import because of AttributeError: module 'matplotlib'

### ISSUE THREAD

**Issue by Borda** [pycaret/pycaret#3853]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Installing the latest version from pip and failing to import the regressor on Kaggle kernel

### Reproducible Example

```python
from pycaret.regression import RegressionExperiment
```

### Expected Behavior

just load the class

### Actual Results

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 1
----> 1 from pycaret.regression import RegressionExperiment

File /opt/conda/lib/python3.10/site-packages/pycaret/regression/__init__.py:1
----> 1 from pycaret.regression.functional import (
      2     add_metric,
      3     automl,
      4     blend_models,
      5     check_drift,
      6     check_fairness,
      7     compare_models,
      8     convert_model,
      9     create_api,
     10     create_app,
     11     create_docker,
     12     create_model,
     13     dashboard,
     14     deploy_model,
     15     ensemble_model,
     16     evaluate_model,
     17     finalize_model,
     18     get_allowed_engines,
     19     get_config,
     20     get_current_experiment,
     21     get_engine,
     22     get_leaderboard,
     23     get_logs,
     24     get_metrics,
     25     interpret_model,
     26     load_experiment,
     27     load_model,
     28     models,
     29     plot_model,
     30     predict_model,
     31     pull,
     32     remove_metric,
     33     save_experiment,
     34     save_model,
     35     set_config,
     36     set_current_experiment,
     37     setup,
     38     stack_models,
     39     tune_model,
     40 )
     41 from pycaret.regression.oop import RegressionExperiment
     43 __all__ = [
     44     "RegressionExperiment",
     45     "setup",
   (...)
     82     "check_drift",
     83 ]

File /opt/conda/lib/python3.10/site-packages/pycaret/regression/functional.py:10
      8 from pycaret.internal.parallel.parallel_backend import ParallelBackend
      9 from pycaret.loggers.base_logger import BaseLogger
---> 10 from pycaret.regression.oop import RegressionExperiment
     11 from pycaret.utils.constants import DATAFRAME_LIKE, SEQUENCE_LIKE, TARGET_LIKE
     12 from pycaret.utils.generic import check_if_global_is_not_none

File /opt/conda/lib/python3.10/site-packages/pycaret/regression/oop.py:16
     10 from pycaret.containers.metrics.regression import get_all_metric_containers
     11 from pycaret.containers.models.regression import (
     12     ALL_ALLOWED_ENGINES,
     13     get_all_model_containers,
     14     get_container_default_engines,
     15 )
---> 16 from pycaret.internal.display import CommonDisplay
     17 from pycaret.internal.logging import get_logger
     18 from pycaret.internal.parallel.parallel_backend import ParallelBackend

File /opt/conda/lib/python3.10/site-packages/pycaret/internal/display/__init__.py:1
----> 1 from pycaret.internal.display.display import CommonDisplay, DummyDisplay
      2 from pycaret.utils.generic import enable_colab
      4 __all__ = ["CommonDisplay", "DummyDisplay", "enable_colab"]

File /opt/conda/lib/python3.10/site-packages/pycaret/internal/display/display.py:7
      1 # Module: internal.display class
      2 # Author: Antoni Baum (Yard1) <antoni.baum@protonmail.com>
      3 # License: MIT
      5 from typing import Any, Dict, List, Optional
----> 7 from pycaret.internal.display.display_backend import SilentBackend, detect_backend
      8 from pycaret.internal.display.display_component import MonitorDisplay
      9 from pycaret.internal.display.progress_bar import ProgressBarDisplay

File /opt/conda/lib/python3.10/site-packages/pycaret/internal/display/display_backend.py:234
    227         return backend
    229     raise TypeError(
    230         f"Wrong backend type. Expected None, str or DisplayBackend, got {type(backend)}."
    231     )
--> 234 detect_backend()

File /opt/conda/lib/python3.10/site-packages/pycaret/internal/display/display_backend.py:205, in detect_backend(backend)
    202     if IN_COLAB:
    203         return ColabBackend()
--> 205     return JupyterBackend()
    207 if isinstance(backend, str):
    208     backends: Dict[str, Any] = {
    209         b.id: b
    210         for b in {
   (...)
    216         }
    217     }

File /opt/conda/lib/python3.10/site-packages/pycaret/internal/display/display_backend.py:132, in JupyterBackend.__init__(self)
    131 def __init__(self) -> None:
--> 132     _enable_matplotlib_inline()
    133     self._display_ref: Optional[DisplayHandle] = None

File /opt/conda/lib/python3.10/site-packages/pycaret/internal/display/display_backend.py:34, in _enable_matplotlib_inline()
     33 def _enable_matplotlib_inline():
---> 34     get_ipython().run_line_magic("matplotlib", "inline")

File /opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py:2417, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2415     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2416 with self.builtin_trap:
-> 2417     result = fn(*args, **kwargs)
   2419 # The code below prevents the output from being displayed
   2420 # when using magics with decodator @output_can_be_silenced
   2421 # when the last Python token in the expression is a ';'.
   2422 if getattr(fn, magic.MAGIC_OUTPUT_CAN_BE_SILENCED, False):

File /opt/conda/lib/python3.10/site-packages/IPython/core/magics/pylab.py:99, in PylabMagics.matplotlib(self, line)
     97     print("Available matplotlib backends: %s" % backends_list)
     98 else:
---> 99     gui, backend = self.shell.enable_matplotlib(args.gui.lower() if isinstance(args.gui, str) else args.gui)
    100     self._show_matplotlib_backend(args.gui, backend)

File /opt/conda/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3603, in InteractiveShell.enable_matplotlib(self, gui)
   3599         print('Warning: Cannot change to a different GUI toolkit: %s.'
   3600                 ' Using %s instead.' % (gui, self.pylab_gui_select))
   3601         gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
-> 3603 pt.activate_matplotlib(backend)
   3604 configure_inline_support(self, backend)
   3606 # Now we must activate the gui pylab wants to use, and fix %run to take
   3607 # plot updates into account

File /opt/conda/lib/python3.10/site-packages/IPython/core/pylabtools.py:360, in activate_matplotlib(backend)
    355 # Due to circular imports, pyplot may be only partially initialised
    356 # when this function runs.
    357 # So avoid needing matplotlib attribute-lookup to access pyplot.
    358 from matplotlib import pyplot as plt
--> 360 plt.switch_backend(backend)
    362 plt.show._needmain = False
    363 # We need to detect at runtime whether show() is called by the user.
    364 # For this, we wrap it into a decorator which adds a 'called' flag.

File /opt/conda/lib/python3.10/site-packages/matplotlib/pyplot.py:295, in switch_backend(newbackend)
    289     locals().update(vars(backend_mod))
    291 # However, the newer approach for defining new_figure_manager (and, in
    292 # the future, show) is to derive them from canvas methods.  In that case,
    293 # also update backend_mod accordingly; also, per-backend customization of
    294 # draw_if_interactive is disabled.
--> 295 if new_figure_manager is None:
    296     def new_figure_manager_given_figure(num, figure):
    297         return canvas_class.new_manager(figure, num)

File /opt/conda/lib/python3.10/site-packages/matplotlib/_api/__init__.py:224, in caching_module_getattr.<locals>.__getattr__(name)
    222 if name in props:
    223     return props[name].__get__(instance)
--> 224 raise AttributeError(
    225     f"module {cls.__module__!r} has no attribute {name!r}")

AttributeError: module 'matplotlib' has no attribute 'backend_bases'
```

### Installed Versions

<details>
matplotlib                               3.6.0
matplotlib-inline                        0.1.6
matplotlib-venn                          0.11.9
pycaret                                  3.2.0
</details>

**Comment by Borda** [comment]
seems that import works with `matplotlib==3.3.4`

**Comment by Borda** [comment]
so far, all seem to be working with `pip install pycaret[full] "matplotlib==3.4.*"`

**Comment by ignacioalbornoz** [comment]
`pip install pycaret[full] "matplotlib==3.4.*"`  doesnt work for me i get

`
Failed to build matplotlib
ERROR: Could not build wheels for matplotlib, which is required to install pyproject.toml-based projects
`

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
