### ISSUE TITLE
[BUG]: AttributeError: 'CatBoostClassifier' object has no attribute 'steps' while trying to tune catboostclassifier model

### ISSUE THREAD

**Issue by Prashavu** [pycaret/pycaret#2859]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

supervised_experiment.py throws error 
[/usr/local/lib/python3.7/dist-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py](https://localhost:8080/#) in predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose, ml_usecase, preprocess)
   4920             pipeline = deepcopy(estimator)
   4921             # Temporarily remove final estimator so it's not used for transform
-> 4922             final_step = pipeline.steps[-1]
   4923             estimator = final_step[-1]
   4924             pipeline.steps = pipeline.steps[:-1]

AttributeError: 'CatBoostClassifier' object has no attribute 'steps'

### Reproducible Example

```python
!pip install --pre pycaret
!pip install pycaret[models]
from pycaret.datasets import get_data
juice = get_data('juice')
from pycaret.classification import *
setup(data = juice,  target = 'Purchase')
catboost = create_model('catboost')
catboostt = tune_model(catboost,optimize = 'F1',return_train_score=True)
```

### Expected Behavior

should throw no error 

### Actual Results

```python-traceback
supervised_experiment.py throws error 
[/usr/local/lib/python3.7/dist-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py](https://localhost:8080/#) in predict_model(self, estimator, data, probability_threshold, encoded_labels, raw_score, drift_report, round, verbose, ml_usecase, preprocess)
   4920             pipeline = deepcopy(estimator)
   4921             # Temporarily remove final estimator so it's not used for transform
-> 4922             final_step = pipeline.steps[-1]
   4923             estimator = final_step[-1]
   4924             pipeline.steps = pipeline.steps[:-1]

AttributeError: 'CatBoostClassifier' object has no attribute 'steps'
```

### Installed Versions

<details>
2.3.10.
</details>

**Comment by tvdboom** [comment]
See #2769. This has already been solved in `master` and will be available with next release.

**Comment by Prashavu** [comment]
@tvdboom so what do we do to make it work with 3.0.0.rc3?

**Comment by celestinoxp** [comment]
> @tvdboomentão o que fazemos para que funcione com o 3.0.0.rc3?

You need wait for rc4 or try make a build. Note: can be instable.

-uninstall pycaret
-install pycaret from source (need git installed)
- use `pip install -U git+https://github.com/pycaret/pycaret.git@master`

**Comment by Prashavu** [comment]
> > @tvdboomentão o que fazemos para que funcione com o 3.0.0.rc3?
> 
> You need wait for rc4 or try make a build. Note: can be instable.
> 
> -uninstall pycaret -install pycaret from source (need git installed)
> 
> * use `pip install -U git+https://github.com/pycaret/pycaret.git@master`
> 
> Note: when rc4 is released you should uninstall this version and use rc4 version!

ok!
